---
# playbook to install and configure general components of Apache
- name: Install apache
  apt:
    state: present
    name:
      - apache2

- name: Replace ports.conf
  template:
    src: "ports.conf.j2"
    dest: "/etc/apache2/ports.conf"

# Apache mpm modules need to be handled separately, see
- name: Change apache worker
  apache2_module:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    ignore_configcheck: True
  with_items:
    - { name: "mpm_event",   state: "absent"  }
    - { name: "mpm_prefork", state: "present" }
  become: yes
  notify: Restart Apache

- name: Enable correct apache modules
  apache2_module:
    state: "{{ item.value }}"
    name: "{{ item.key }}"
    ignore_configcheck: True
  with_dict:
    status: present
    cgid: present
    cgi: present
    actions: present
    alias: present
    rewrite: present
    authn_core: present
    authz_user: present
    ssl: present

  notify: Restart Apache

