---
- include_vars: comanage_idp.yml

- name: perform apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 1
  become: Yes

- name: ensure that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages  }}"
  become: Yes

- name: Ensure directory exists
  file:
    path: "{{ idp_mellon_path }}"
    state: directory
    owner: www-data
    mode: 0755

- name: Get the IdP metadata
  get_url:
    url: "{{ idp_metadata_url }}"
    dest: "{{ idp_metadata_path }}"
    owner: www-data
    mode: 0600
    validate_certs: no

# Finally add a RewriteRule to the CoManage .htaccess to allow redirection of the
# sp metadata to a convenient URL
- name: Add rewrite rule for SP metadata
  blockinfile:
    block: "RewriteRule  \"^/auth/sp/metadata$\" \"/etc/apache2/mellon/sp-metadata.xml\""
    follow: yes
    insertafter: "RewriteRule.*$"
    path: "{{ comanage_path }}/.htaccess"
  notify:
    - restart apache

