---
- name: Copy create_db file
  copy:
    src: "create_db.sql"
    dest: /tmp

- name: Copy foreign keys file
  copy:
    src: "fkeys.sql"
    dest: /tmp

- name: Copy views file
  copy:
    src: "views.sql"
    dest: /tmp

- name: create database for CoManage-Proxy linkup
  command: >
    mysql --batch --silent --raw --database "{{ comanage_proxy_db_name }}"
          --execute "source /tmp/create_db.sql"
  register: tablecreation
  changed_when: tablecreation.stderr is not search("45000.*table exists")
  become: Yes

- name: create foreign key relations for CoManage-Proxy linkup
  command: >
    mysql --batch --silent --raw --database "{{ comanage_proxy_db_name }}"
          --execute "source /tmp/fkeys.sql"
  register: keycreation
  changed_when: keycreation.stderr is not search("45000.*key exists")
  become: Yes

- name: create views for CoManage-Proxy linkup
  command: >
    mysql --batch --silent --raw --database "{{ comanage_proxy_db_name }}"
          --execute "source  /tmp/views.sql"
  register: viewcreation
  changed_when: viewcreation.stderr is not search("45000.*view exists")
  become: Yes

- name: create user for mysql with all privilege
  mysql_user:
    name: "{{ comanage_proxy_db_user }}"
    host: "%"
    password: "{{ comanage_proxy_db_password }}"
    priv: "{{ comanage_proxy_db_name }}.*:ALL"
    state: present
  notify:
    - Restart MySQL
  become: Yes

# Create Attribues Hash database
- name: Copy hash_db file
  copy:
    src: "create_attributes_hash_db.sql"
    dest: /tmp/create_attributes_hash_db.sql

- name: create satosa attributes_hash table
  mysql_db:
    name: "{{ satosa_db_name }}"
    state: import
    target: /tmp/create_attributes_hash_db.sql

- name: create user for mysql with all privilege
  mysql_user:
    name: "{{ satosa_db_user }}"
    host: "%"
    password: "{{ satosa_db_password }}"
    priv: "{{ satosa_db_name }}.*:ALL"
    state: present
  notify:
    - Restart MySQL

- name: Install backup script
  template:
    src: "satosa_mysql_backup.sh.j2"
    dest: "{{backup_runparts}}/satosa_mysql_backup.sh"
    mode: 0755
