---
- name: create database for CoManage-Proxy linkup
  mysql_db:
    name: "{{ comanage_proxy_db_name }}"
    state: present

- name: create user for mysql with all privilege
  mysql_user:
    name: "{{ comanage_proxy_db_user }}"
    password: "{{ comanage_proxy_db_password }}"
    priv: "{{ comanage_proxy_db_name }}.*:ALL"
    state: present
  notify:
    - Restart MySQL
