---
- name: create database for proxy-comanage interface
  mysql_db:
    name: "{{ comanage_proxy_db }}"
    state: present

- name: create user for mysql with all privilege
  mysql_user:
    name: "{{ comanage_proxy_db_user }}"
    password: "{{ comanage_proxy_db_password }}"
    priv: "{{ comanage_proxy_db }}.*:ALL"
    state: present
  notify:
    - Restart MySQL
