---
attributes:
  uid:
    openid: [uid]
    saml:
      - 'urn:mace:dir:attribute-def:uid'
      - 'urn:oid:0.9.2342.19200300.100.1.1'
#      - 'uid'
  address:
    openid: [address.street_address]
    saml:
      - 'urn:mace:dir:attribute-def:postalAddress'
      - 'urn:oid:2.5.4.16'
#      - 'postalAddress'
  displayName:
    openid: [nickname]
    saml:
      - 'urn:mace:dir:attribute-def:displayName'
      - 'urn:oid:2.16.840.1.113730.3.1.241'
#      - 'displayName'
  givenname:
    openid: [given_name]
    saml:
      - 'urn:mace:dir:attribute-def:givenName'
      - 'urn:oid:2.5.4.42'
#      - 'givenName'
  mail:
    openid: [email]
    saml:
      - 'urn:mace:dir:attribute-def:mail'
      - 'urn:oid:0.9.2342.19200300.100.1.3'
#      - 'mail'
  name:
    openid: [name]
    saml:
      - 'urn:mace:dir:attribute-def:cn'
      - 'urn:oid:2.5.4.3'
#      - 'cn'
  surname:
    openid: [family_name]
    saml:
      - 'urn:mace:dir:attribute-def:sn'
      - 'urn:oid:2.5.4.4'
#      - 'sn'
  isMemberOf:
    openid: [edumember_is_member_of]
    saml:
      - 'urn:mace:dir:attribute-def:isMemberOf'
      - 'urn:oid:1.3.6.1.4.1.5923.1.5.1.1'
#      - 'isMemberOf'
  schacHomeOrganization:
    openid: [schac_home_organisation]
    saml:
      - 'urn:mace:terena.org:attribute-def:schacHomeOrganization'
      - 'urn:oid:1.3.6.1.4.1.25178.1.2.9'
  edupersontargetedid:
    openid: [eduperson_targeted_id]
    saml:
      - 'urn:mace:dir:attribute-def:eduPersonTargetedID'
      - 'urn:oid:1.3.6.1.4.1.5923.1.1.1.10'
#      - 'eduPersonTargetedID'
  eduPersonPrincipalName:
    openid: [eduperson_principalname]
    saml:
      - 'urn:mace:dir:attribute-def:eduPersonPrincipalName'
      - 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6'
#      - 'eduPersonPrincipalName'
  eduPersonScopedAffiliation:
    openid: [eduperson_scoped_affiliation]
    saml:
      - 'urn:mace:dir:attribute-def:eduPersonScopedAffiliation'
      - 'urn:oid:1.3.6.1.4.1.5923.1.1.1.9'
#      - 'eduPersonScopedAffiliation'
  eduPersonAffiliation:
    openid: [eduperson_affiliation]
    saml:
      - 'urn:mace:dir:attribute-def:eduPersonAffiliation'
      - 'urn:oid:1.3.6.1.4.1.5923.1.1.1.1'
#      - 'eduPersonAffiliation'
  eduPersonEntitlement:
    openid: [eduperson_entitlement]
    saml:
      - 'urn:mace:dir:attribute-def:eduPersonEntitlement'
      - 'urn:oid:1.3.6.1.4.1.5923.1.1.1.7'
#      - 'eduPersonEntitlement'
