---
sudo: required

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      - surfnet-nl:tEtfF52tuZaz02sdjLJ2XGUY

language: python
python:
  - 3.6

cache:
  pip: true
  directories:
    - "$HOME/docker"

git:
  submodules: false

addons:
  apt:
    packages:
      - bridge-utils
      - python3-jinja2
      - python3-yaml

before_install:
  - >
    if [ -d $HOME/docker ]; then
      ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load";
    fi
  - sudo pip install yamllint
  - sudo wget https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb -P /tmp
  - sudo dpkg -i /tmp/vagrant_2.1.2_x86_64.deb
  - sudo apt-add-repository -y ppa:ansible/ansible-2.6
  - sudo apt -q update
  - sudo apt -y install ansible

script:
  - sudo ./scripts/travis_tests

before_cache:
  - mkdir -p $HOME/docker
  - "docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' \
        | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz \
             || docker save $0 | gzip -c6 > $HOME/docker/$1.tar.gz' "
