---
# Use containers instead of full VMs for faster startup.
sudo: required

services:
  - docker

notifications:
  # default: send to commiter
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: "c7ePudQmb7/kQKJLl+oW9FWLvnX/PaErT5TvTxmK3r7onx1tjEGoLwKGN0qFY0OC6WA6mDBnn6IpK/M\
               wb1fTVosZiZgmp/NB6at6ZpiVnQjafv2Q8ca363S1n2SLWV/3oZqCwGvbGCH9OW84lTjRLCHEjayio9\
               m9HZ1E1apxd9NVNwktlKqEegjqA7kFDpc6FP3o8ofjggEEg4traic5ZDR/aI1/kV2nwILpc3Uzc3q9m\
               z1B0g6/hd68LnjGSpGN5pk/qihAAX1ZUlQ6t+nhlStdT/dTr9LzL+vEaTkvGL/VB+wf36dxW/2NenJG\
               P673Qgmqj5pLf6TLuGlsDfleFcroRIrLH9IXHIvsTslaPYKIGwRAvlTsEA6gVauoe1qhH1iabswuE6v\
               7e8HZyYjoFYzE9DpoMINt7iYDR8x5+aEqQ3UEz18Mge4nMLfSc4L4t+5nLSso3z/Al8ptSzloc+1WPI\
               ufPrMfX0ZsyazA0ZaHFzF84uBXlanRBrN2q1G+2SRxobI/WmOvYatNHegxJ8218lQ+54MS6UOrSJBNW\
               A/+ObZkcTTKOAe6O6jrEVW0T3oVfe4iATuLBIl5BVb6c8p+EZF9BmgW6VApRlIci78UDDbwvNEZw+/H\
               gnvocXZxh0B0wQLu4KLxpPLlE2hiWVl4f+jMFdVdxIeZEGEh2cQ="

# the syntax check scripts as well as yamllint need python3
language: python
python:
  - 3.6

# cache the docker images
cache:
  pip: true
  directories:
    - $HOME/docker

# disable the default submodule logic, as travis can't reach gitlab anyway
git:
  submodules: false

addons:
  apt:
    packages:
      - bridge-utils
      - python3-jinja2
      - python3-yaml

before_install:
  # Load cached docker images
  - >
    if [ -d $HOME/docker ];
    then
      ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load";
    fi
  - sudo pip install yamllint
  - sudo wget https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb -P /tmp
  - sudo dpkg -i /tmp/vagrant_2.1.2_x86_64.deb
  - sudo apt-add-repository -y ppa:ansible/ansible-2.6
  - sudo apt -q update
  - sudo apt -y install ansible

script:
  - sudo ./scripts/travis_tests

before_cache:
  # Save tagged docker images
  - "mkdir -p $HOME/docker"
  - "docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' \
       | xargs -n 2 -t sh \
         -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -c6 > $HOME/docker/$1.tar.gz' \
    "
