---
# Use containers instead of full VMs for faster startup.
sudo: false
notifications:
  email:
    recipients:
      - scz@list.surfnet.nl
    on_success: change
    on_failure: always
  slack:
    secure: "DTgBggmvvq0eWtCAG7N/ij3gKN2OOna/kjRBRTbk4Zm9Q7xE5j1+d8li46b1oO91l2cz0EhdjkPwusX5LHcoy0xoVQcYpqSGOwGX/MShOdl/ZjuyiorvzMHYD2aL/s7ZlTJWXGppoiUy1Vhl0aEQ/o2Rx8wYT7BANPdSVIMImfhhzenC1pnD+wMeqnsSn6Go/vpdUUrhakeJmTEGsJ9rdWiqjXlB/5hrTiy2/d4e0dqZAawbhLn19oZc7BVUfiFpF9HMd2dZ1H25gkUV7yW4c4lisdF6zGStfB6JmK5YBQuyoyqr1wgEYtkhKWQDMuhY0EOCjCwInF7huljCWassp5CFUqVWOzAJRTGxdrGhzeNB/jBI7KnS+KaI0AhFvGlqWrDT7UW1dldLyph1DzD7upHBFRGLFtIbdj7dAWxsQjprVdbsz7hwbGRX9STHzBwzZ3UXbnWQKUTJ/iBsNI9h6c0Oxu4QeqpdX2Gp5F9dshpdjb9utHlbQTlLMI9bTEsnYHPk9YFFKKPNgxx2H5hrlKEZxACGDbQQ0kjre7539hHBbg52fOhht5bI+aAhFzKMACfO4D6pkKUWFMhTWjTFanJbalMzHF2REvN5BgA6GWiC4E9sDV0ws7LV0BzBfkP5+QFZmUoztqB75HZQFtsaIiLmxlSRtFN22fW++1y/t6I="

# the syntax check scripts as well as yamllint need python3
language: python
cache: pip
python:
  - 3.5

# disable the default submodule logic, as travis can't reach gitlab anyway
git:
  submodules: false

install:
  - pip install yamllint
  - pip install jinja2

script:
  - "./scripts/syntax-check"
  - yamllint .
