---
# Use containers instead of full VMs for faster startup.
sudo: required

services:
  - docker

notifications:
  # default: send to commiter
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      - "surfnet-nl:hWCPDj2K9KVEPYrSmE16q4CM"

# the syntax check scripts as well as yamllint need python3
language: python
python:
  - 3.6

# cache the docker images
cache:
  pip: true
  directories:
    - $HOME/docker

# disable the default submodule logic, as travis can't reach gitlab anyway
git:
  submodules: false

addons:
  apt:
    packages:
      - bridge-utils
      - python3-jinja2
      - python3-yaml

before_install:
  # Load cached docker images
  - >
    if [ -d $HOME/docker ];
    then
      ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load";
    fi
  - sudo pip install yamllint
  - sudo wget https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb -P /tmp
  - sudo dpkg -i /tmp/vagrant_2.1.2_x86_64.deb
  - sudo apt-add-repository -y ppa:ansible/ansible-2.6
  - sudo apt -q update
  - sudo apt -y install ansible

script:
  - "                      ./scripts/syntax-check        ||  travis_terminate 1"
  - "sudo                  ./start-vm --provider docker  ||  travis_terminate 1"
  - "sudo env REEANTRANT=1 ./start-vm --provider docker  ||  travis_terminate 1"

before_cache:
  # Save tagged docker images
  - "mkdir -p $HOME/docker"
  - "docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' \
       | xargs -n 2 -t sh \
         -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -c6 > $HOME/docker/$1.tar.gz' \
    "
