---
sudo: required

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      - surfnet-nl:tEtfF52tuZaz02sdjLJ2XGUY

language: python
python:
  - 3.6

cache:
  pip: true
  directories:
    - "$HOME/docker"

git:
  submodules: false

before_install:
  - >
    if [ -d $HOME/docker ]; then
      for f in $HOME/docker/*.tar.gz;
      do
        echo "Loading '$f' into docker";
        zcat "$f" | sudo docker load || true;
      done;
    fi
  - pip install yamllint jinja2 pyyaml
  - sudo wget https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb -P /tmp
  - sudo dpkg -i /tmp/vagrant_2.1.2_x86_64.deb
  - sudo apt-add-repository -y ppa:ansible/ansible-2.6
  - sudo apt -q update
  - sudo apt -y install ansible bridge-utils
  - sudo adduser travis docker

script:
  - ./scripts/travis_tests

before_cache:
  - "rm -rf $HOME/docker"
  - "mkdir -p $HOME/docker"
  - "docker save scz-base | gzip -c6 > $HOME/docker/scz-base.tar.gz' "
  - "ls -la $HOME/docker"
