---
# Use containers instead of full VMs for faster startup.
sudo: false

# the syntax check scripts as weel as yamllint need python3
language: python
python:
  - 3.5

# disable the default submodule logic, as travis can't reach gitlab anyway
git:
  submodules: false

install:
  - pip install yamllint
  - pip install jinja2

script:
  - ./scripts/syntax-check
  - yamllint .

