---
sudo: required

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      - surfnet-nl:tEtfF52tuZaz02sdjLJ2XGUY

language: python
python:
  - 3.6

cache:
  pip: true
  directories:
    - "$HOME/docker"

git:
  submodules: false

before_install:
  - "ls -la $HOME/docker/"
  - "sudo ls -la /var/lib/docker/"
  - >
    if [ -d $HOME/docker ]; then
      find $HOME/docker -type f -size -1k -print0 | xargs -0 rm -f;
      for f in $HOME/docker/*.tar.gz;
      do
        echo "Loading '$f' into docker";
        zcat "$f" | sudo docker load;
      done;
    fi
  - pip install yamllint jinja2 pyyaml
  - sudo wget https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb -P /tmp
  - sudo dpkg -i /tmp/vagrant_2.1.2_x86_64.deb
  - sudo apt-add-repository -y ppa:ansible/ansible-2.6
  - sudo apt -q update
  - sudo apt -y install ansible bridge-utils
  - sudo adduser travis docker

script:
  - ./scripts/travis_tests

before_cache:
  - "rm -rf $HOME/docker"
  - "mkdir -p $HOME/docker"
  - "docker image ls -a"
  - "docker container kill $(docker ps -q)"
  - "docker container prune -f"
  - "docker image prune -f"
  - "docker image ls -a"
  - "docker images -a --format '{{.Repository}}:{{.Tag}} {{.ID}}' \
        | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz \
             || docker save $0 | gzip -c6 > $HOME/docker/$1.tar.gz' "
  - "ls -la $HOME/docker"
