---
sudo: required

language:
  - bash
  - python

# disable the default submodule logic
git:
  submodules: "false"


before_install:
  - sudo apt install ansible yamllint

script:
  - ./scripts/syntax-check
  - yamllint .

