# vim:ts=2:sw=2:expandtab
---
- hosts: all
  tasks:
  - name: Read vars from secrets file
    include_vars: "{{ secrets_file }}"
    tags: always
    check_mode: no

# looks hackish, but this is apparently the "a clean, official way" to gather
# required facts from all hosts, regardless of the commandline --limit
# parameter
# We need this here, because in the group vars, we rely on the hostvars for
# the ip addresses of other hosts (e.g, mgnt1)
- hosts: all
  pre_tasks:
  - name: Gather facts from mgnt hosts (regardless of limit or tags)
    setup:
    delegate_to: "{{item}}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{groups['all']}}"

- hosts: all
  roles:
    - { role: basic,    tags: ['common'], when: not preinstalled }
    - { role: apt,      tags: ['common'] }
    - { role: firewall, tags: ['common'] }
    - { role: ntp,      tags: ['common'], when: not preinstalled }
    - { role: users,    tags: ['common'], when: not preinstalled }
#   - { role: logging,  tags: ['logging'  ] }

- hosts: mgnt1
  #  roles:
  #  - { role: ldap, tags: ['ldap'] }
  #  - { role: mta,  tags: ['mta' ] }

- hosts: mgnt2
  #roles:
  #  - { role: logstash, tags: ['logstash'] }
  #  - { role: logstash, tags: ['logstash'] }

- hosts: lb
  roles:
  - { role: http_nginx,      tags: ['http_nginx']      }
  - { role: tls_letsencrypt, tags: ['tls_letsencrypt'] }
  - { role: https_haproxy,   tags: ['https_haproxy','test']   }

- hosts: comanage
  roles:
   - { role: http_apache, tags: ['comanage'] }
   - { role: postfix, tags: ['comanage'] }
   - { role: mysql, tags: ['comanage'] }
   - { role: php56, tags: ['comanage'] }
   - { role: auth_mellon, tags: ['comanage'] }
   - { role: comanage, tags: ['comanage'] }
   - { role: comanage_idp, tags: ['comanage'] }
   - { role: comanage_enable, tags: ['comanage'] }

- hosts: ldap
  roles:
      #    - { role: ldap, tags: ['ldap'] }

- hosts: proxy
  roles:
      - { role: http_dummy,  tags: ['proxy','test'  ] }
      #    - { role: satosa,  tags: ['satosa'  ] }
      #    - { role: pyff,    tags: ['pyff'    ] }
      #    - { role: wayf,    tags: ['wayf'    ] }
      #    - { role: mongodb, tags: ['mongodb' ] }

- hosts: metadata
  roles:
      #    - { role: mongodb,      tags: ['mongodb'     ] }
      #    - { role: metadata-api, tags: ['metadata-api'] }

