---
- hosts: all
  tasks:
  - name: Read vars from secrets file
    include_vars: "{{ secrets_file }}"
    tags: always
    check_mode: no

# looks hackish, but this is apparently the "a clean, official way" to gather
# required facts from all hosts, regardless of the commandline --limit
# parameter
# We need this here, because in the group vars, we rely on the hostvars for
# the ip addresses of other hosts (e.g, mgnt1)
- hosts: all
  pre_tasks:
  - name: Gather facts from mgnt hosts (regardless of limit or tags)
    setup:
    delegate_to: "{{item}}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{groups['mgnt']}}"

- hosts: all
  roles:
    - { role: basic,    tags: ['common'] }
    - { role: apt,      tags: ['common'] }
    - { role: firewall, tags: ['common'] }
    - { role: ntp,      tags: ['common'] }
    - { role: users,    tags: ['common'] }
#   - { role: logging,  tags: ['logging'  ] }

- hosts: mgnt1
  #  roles:
  #  - { role: ldap, tags: ['ldap'] }
  #  - { role: mta,  tags: ['mta' ] }

- hosts: mgnt2
  #roles:
  #  - { role: logstash, tags: ['logstash'] }
  #  - { role: logstash, tags: ['logstash'] }


- hosts: comanage
  roles:
      #    - { role: postgres, tags: ['postgres'] }
      #    - { role: comanage, tags: ['comanage'] }

- hosts: ldap
  roles:
      #    - { role: ldap, tags: ['ldap'] }

- hosts: proxy
  roles:
      #    - { role: satosa,  tags: ['satosa'  ] }
      #    - { role: pyff,    tags: ['pyff'    ] }
      #    - { role: wayf,    tags: ['wayf'    ] }
      #    - { role: mongodb, tags: ['mongodb' ] }

- hosts: metadata
  roles:
      #    - { role: mongodb,      tags: ['mongodb'     ] }
      #    - { role: metadata-api, tags: ['metadata-api'] }

- hosts: loadbalancer
  roles:
      #    - { role: sslcerts, tags: ['sslcerts'] }
      #    - { role: haproxy,  tags: ['haproxy' ] }

