# vim:ts=2:sw=2:expandtab
---
- hosts: all
  tasks:
    - name: Read vars from secrets file
      include_vars: "{{ secrets_file }}"
      tags: always
      check_mode: "no"

# looks hackish, but this is apparently the "a clean, official way" to gather
# required facts from all hosts, regardless of the commandline --limit
# parameter
# We need this here, because in the group vars, we rely on the hostvars for
# the ip addresses of other hosts (e.g, mgnt1)
- hosts: all
  pre_tasks:
    - name: Gather facts from mgnt hosts (regardless of limit or tags)
      setup:
      delegate_to: "{{item}}"
      delegate_facts: "true"
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{groups['all']}}"
      tags: always

- hosts: all
  roles:
    - { role: basic,    tags: ['common'] }
    - { role: apt,      tags: ['common'] }
    - { role: firewall, tags: ['common'] }
    - { role: ntp,      tags: ['common'] }
    - { role: users,    tags: ['common'] }
#   - { role: logging,  tags: ['logging'  ] }

- hosts: mgnt1
  roles:
  #  - { role: ldap, tags: ['ldap'] }
  #  - { role: mta,  tags: ['mta' ] }

- hosts: mgnt2
  roles:
  #  - { role: logstash, tags: ['logstash'] }
  #  - { role: logstash, tags: ['logstash'] }

- hosts: lb
  roles:
    - { role: http_nginx,      tags: ['lb','http_nginx'     ] }
    - { role: tls_letsencrypt, tags: ['lb','tls_letsencrypt'] }
    - { role: https_haproxy,   tags: ['lb','https_haproxy'  ] }

- hosts: comanage
  roles:
    - { role: http_dummy,  tags: ['proxy','test'] }

- hosts: ldap
  roles:

- hosts: proxy
  roles:
    - { role: http_dummy,  tags: ['proxy','test'] }

- hosts: client
  roles:
    - { role: http_dummy,  tags: ['client','test'] }

- hosts: metadata
  roles:

