---
- name: set up apt repo
  template: src=sources.list.j2 dest=/etc/apt/sources.list force=yes

- name: Update apt cache
  apt: update_cache=yes
  changed_when: False

- name: Upgrade packages
  apt: upgrade=dist

- name: Install common tools / clients
  apt: name={{ item }} state=present
  with_items:
     - sudo
     - bash
     - zsh
     - locales-all
     - open-vm-tools
     - open-vm-tools-dkms

