---
- name: set up apt repo
  template: src=sources.list.j2 dest=/etc/apt/sources.list force=yes

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade packages
  apt: upgrade=dist

- name: Install common tools / clients
  apt: name={{ item }} state=present
  with_items:
     - sudo
     - bash
     - locales-all


