---
- name: write version of role
  lineinfile:
    path: "/opt/sram-deploy.log"
    create: true
    state: present
    insertafter: "EOF"
    line: "{{datetime_now.stdout}} {{ansible_user}} {{ansible_play_name}} \
      {{git_version.results[0].stdout}} {{git_version.results[1].stdout}}"
  changed_when: false
