---
- name: Ensure that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - libxml2-dev
    - libxmlsec1-dev

- name: fetch PAM WebSSO from {{ pam_websso.repo_url }}, version {{ pam_websso.repo_version }}
  git:
    repo: "{{ pam_websso.repo_url }}"
    dest: "{{ pam_websso.project_dir }}"
    version: "{{ pam_websso.repo_version }}"
    accept_hostkey: "yes"
    force: "yes"
  register: pam_websso_git

- name: install PAM WebSSO
  pip:
    name: "{{ pam_websso.project_dir }}"
    state: latest
  when: pam_websso_git.changed

- name: install PAM WebSSO settings
  template:
    src: "settings.json.j2"
    dest: "{{ pam_websso.project_dir }}/settings.json"

- name: Create WebSSO daemon systemd service file
  template:
    src: websso-daemon.service.j2
    dest: "{{ pam_websso.project_dir }}/websso-daemon.service"
    mode: 0644

- name: Copy to satosa.service in /etc/systemd/system
  copy:
    src: "{{ pam_websso.project_dir }}/websso-daemon.service"
    dest: /etc/systemd/system/websso-daemon.service
    remote_src: yes

- name: restart WebSSO daemon
  systemd: daemon_reload=yes name=websso-daemon state=restarted enabled=yes
