---
- name: Update cache
  command: apt-get update
  args:
    warn: false
  changed_when: false

- name: Ensure that packages are installed
  apt:
    name:
      - mariadb-server
      - python-pymysql
    state: present

- name: listen to public IP
  copy:
    src: 60-scz.cnf
    dest: /etc/mysql/mariadb.conf.d/60-scz.cnf
  notify: restart MariaDB

- name: Add SBS database
  mysql_db:
    name: '{{ sbs_db_name }}'
    encoding: utf8
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add SBS user
  mysql_user:
    name: '{{ sbs_db_user }}'
    host: '%'
    password: '{{ sbs_db_password }}'
    priv: '{{ sbs_db_name }}.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock
