---
- name: Update cache
  command: apt-get update
  args:
    warn: false
  changed_when: false

- name: Ensure that packages are installed
  apt:
    name:
      - mariadb-server
      #- python-pymysql
      - python-mysqldb
    state: present

- name: Create mariadb.service.d directory
  file:
    path: /etc/systemd/system/mariadb.service.d
    state: directory
    mode: '0755'

- name: Set mysql systemd Type=exec
  copy:
    src: type.conf
    dest: /etc/systemd/system/mariadb.service.d/type.conf
  notify: restart MariaDB

- name: listen to public IP
  copy:
    src: 60-scz.cnf
    dest: /etc/mysql/mariadb.conf.d/60-scz.cnf
  notify: restart MariaDB

- name: Add admin user
  mysql_user:
    name: '{{ db_admin_user }}'
    host: '%'
    password: '{{ db_admin_password }}'
    priv: '*.*:ALL,GRANT'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
