---
- name: restart filebeat
  service:  name=filebeat state=restarted
  when: use_logserver
  listen: "restart filebeat"

- name: restart rsyslog
  service:  name=rsyslog state=restarted
  listen: "restart rsyslog"

- name: start filebeat Service
  service: name=filebeat state=restarted enabled=yes
  when: use_logserver

- name: start metricbeat Service
  service: name=metricbeat state=restarted enabled=yes
  when: use_logserver
