---
packages:
  - slapd
  - ldap-utils
  - unzip

eduPersonSchema_ldif: openLdapEduperson-201602DV.ldif
eduPersonSchema_zip: 2xOpenLdapEduPerson-201602.zip
eduPersonSchema_url: >
  https://spaces.internet2.edu/download/attachments/2309/{{ eduPersonSchema_zip }}

ldapPublicKey: openssh-lpk-openldap
ldapPublicKey_ldif: openssh-lpk-openldap.ldif
# avoid Travis yamllint error on line-length....
ldapPKS1: https://raw.githubusercontent.com/AndriiGrytsenko/
ldapPKS2: openssh-ldap-publickey/master/misc/openssh-lpk-openldap.schema
ldapPublicKeySchema_url: "{{ ldapPKS1 }}{{ ldapPKS2 }}"
