---
- include_vars: mysql.yml

- name: ensure that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages  }}"
  become: Yes

- name: Start the MySQL service
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create MySQL users
  mysql_user:
    name: '{{item.name}}'
    password: '{{item.hash}}'
    encrypted: true
    priv: '{{item.priv}}'
    state: present
  with_items: "{{mysql_users}}"

