---
- include_vars: mysql.yml

- name: ensure that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages  }}"
  become: Yes

- name: Start the MySQL service
  service:
    name: mariadb-server
    state: started

