# defines safe default for letsencrypt
#   renew_days: certificate is renewed if is is valid for less than N days
#   use_staging: use Letsencrypt staging servers (use for testing; Letsencrypt
#   prod has rate limiting)
---
letsencrypt:
  use_staging: true
  acme_challenge_dir: "/var/www/certbot"

certbot:
  account_dir: "/etc/letsencrypt/accounts"
  cert_dir: '/etc/letsencrypt/live'
  cert_pem: 'cert.pem'
  chain_pem: 'chain.pem'
  fullchain_pem: 'fullchain.pem'
  privkey_pem: 'privkey.pem'
  all_pem: 'priv+fullchain.pem'
