---

- name: determine Docker container
  shell: cat /proc/self/cgroup | grep systemd | sed "s/.*\(docker\).*/\1/"
  register: docker

- name: set nameservers
  template: src=resolv.conf.j2 dest=/etc/resolv.conf force=yes
  when: docker.stdout_lines[0] != "docker"

- name: set timezone
  file: state=link src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime force=yes

- name: set timezone
  template: src=timezone.j2 dest=/etc/timezone force=yes

- name: set hostname
  hostname: name={{inventory_hostname_short}}
  when: docker.stdout_lines[0] != "docker"

- name: set /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts force=yes
  when: docker.stdout_lines[0] != "docker"

- name: check that hostname and fqdn are set up correctly
  command: "hostname --fqdn"
  any_errors_fatal: true
  changed_when: false
  when: docker.stdout_lines[0] != "docker"

- name: "{{'en' if enable_ipv6 else 'dis'}}able ipv6"
  template: src=99-sysctl-ipv6.conf.j2 dest=/etc/sysctl.d/99-sysctl-ipv6.conf
  register: result_ipv6

- name: reload sysctl settings
  systemd: name=systemd-sysctl.service state=restarted
  when: result_ipv6.changed
  when: docker.stdout_lines[0] != "docker"

- name: install sudo permissions
  template: src=scz-sudo.j2 dest=/etc/sudoers.d/scz-sudo owner=root group=root mode=0600 force=yes

- name: set up ssh config
  template: dest=/etc/ssh/sshd_config src=sshd_config.j2
  notify:
    - restart sshd

