---

- name: set nameservers
  template: src=resolv.conf.j2 dest=/etc/resolv.conf force=yes
  when:
    - not is_aws
    - ansible_virtualization_type != "docker"

- name: fix dhclient.conf
  template: src=dhclient.conf.j2 dest=/etc/dhcp/dhclient.conf force=yes
  when:
    - is_aws
    - ansible_virtualization_type != "docker"
  register: dhclient

- name: Restart networking
  systemd:
    name: networking
    state: restarted
  when: dhclient.changed

- name: set localtime
  file: state=link src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime

- name: set timezone
  template: src=timezone.j2 dest=/etc/timezone

- name: set hostname
  hostname: name={{inventory_hostname_short}}
  when: ansible_virtualization_type != "docker"

- name: set /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts force=yes
  when:
    - not is_aws
    - ansible_virtualization_type != "docker"

- name: check that hostname and fqdn are set up correctly
  command: "/usr/bin/hostname --fqdn"
  any_errors_fatal: true
  changed_when: false
  when: ansible_virtualization_type != "docker"

- name: install journald config
  template:
    src: "journald.conf.j2"
    dest: "/etc/systemd/journald.conf"
  notify: restart journald

- name: "{{'en' if enable_ipv6 else 'dis'}}able ipv6"
  template: src=99-sysctl-ipv6.conf.j2 dest=/etc/sysctl.d/99-sysctl-ipv6.conf
  notify: reload sysctl settings

- name: "Enable dmesg for regular users"
  lineinfile:
    dest: "/etc/sysctl.d/99-user-dmesg.conf"
    create: true
    line: "kernel.dmesg_restrict = 0"
    state: present
  notify: reload sysctl settings

- name: install sudo permissions
  template: src=scz-sudo.j2 dest=/etc/sudoers.d/scz-sudo owner=root group=root mode=0600 force=yes

- name: make sure ed25519 key exists
  command:
    cmd: "ssh-keygen -f '{{item}}' -N '' -t ed25519"
    creates: "{{item}}"
  with_items:
    - "/etc/ssh/ssh_host_ed25519_key"
  notify:
    - restart sshd

- name: set up ssh config
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
  notify:
    - restart sshd

- name: remove obsolete ssh host keys
  file:
    path: "/etc/ssh/ssh_host_{{item}}"
    state: absent
  with_items:
    - "dsa_key"
    - "dsa_key.pub"
    - "rsa_key"
    - "rsa_key.pub"
    - "ecdsa_key"
    - "ecdsa_key.pub"

# Normally ca-certificates does this, but
# the first time apt hasn't run yet
- name: Create ssl_certs_dir
  file:
    path: "{{ ssl_certs_dir }}"
    state: directory
    mode: '0755'

- name: Ensure group "ssl-cert" exists
  group:
    name: ssl-cert
    state: present
    system: true

- name: write backend wildcard key
  copy:
    content: "{{wildcard_backend_cert.priv}}"
    dest: "{{ ssl_certs_dir }}/{{ internal_base_domain }}.key"
    owner: "root"
    group: "ssl-cert"
    mode: 0640

- name: write backend wildcard pub
  copy:
    content: "{{wildcard_backend_cert.pub}}"
    dest: "{{ ssl_certs_dir }}/{{ internal_base_domain }}.crt"
    owner: "root"
    group: "root"
    mode: 0644

- name: write internal certificate
  copy:
    content: "{{wildcard_backend_cert.pub}}"
    dest: "{{ ca_cert_dir }}/sram-internal.crt"
    owner: "root"
    group: "root"
    mode: 0600
  notify: "update certificates"

- name: write https certificate
  copy:
    content: "{{https_cert.cert}}"
    dest: "{{ ca_cert_dir }}/sram-https.crt"
    owner: "root"
    mode: 0600
  when: enable_https and use_fixed_cert
  notify: "update certificates"

- name: remove obsolete files
  file:
    path: "{{ca_cert_dir}}/{{item}}"
    state: "absent"
  with_items:
    - "vm.scz-vm.crt"
    - "scz-vm.crt"
  notify: "update certificates"
