---
sbs_openidc_timeout: 86400

sbs_repository: https://github.com/SURFscz/SBS.git
sbs_version: main

sbs_work_dir: "/opt/sbs"
sbs_git_dir: "{{ sbs_work_dir }}/sbs"
sbs_env_dir: "{{ sbs_work_dir }}/sbs-env"

sbs_db_name: "sbs"
sbs_db_user: "sbs"
sbs_db_host: "localhost"

sbs_mail_host: "{{ mail.relay_to }}"
sbs_mail_port: "25"

sbs_oidc_crypto_password: "CHANGEME"
sbs_uid_attribute: "sub"

sbs_disclaimer_color: "#a29c13"
sbs_disclaimer_label: wsgi

sbs_urn_namespace: "urn:example:sbs"
sbs_restricted_co_default_org: "example.org"

sbs_mail_sender_name: "SURFnet"
sbs_mail_sender_email: "no-reply@surfnet.nl"

sbs_wiki_link: "https://www.example.org/wiki"

sbs_backend_port: 80

sbs_oidc_config_url: "https://{{ hostnames.proxy }}/.well-known/openid-configuration"

sbs_cron_hour_of_day: 4
