---
sbs_openidc_timeout: 86400

sbs_repository: https://github.com/SURFscz/SBS.git
sbs_version: master

sbs_work_dir: "/opt/sbs"
sbs_git_dir: "{{ sbs_work_dir }}/sbs"
sbs_env_dir: "{{ sbs_work_dir }}/sbs-env"

sbs_db_name: "sbs"
sbs_db_user: "sbs"
sbs_db_host: "localhost"

sbs_mail_host: "{{ mail.relay_host }}"
sbs_mail_port: "1025"

sbs_disclaimer_color: "#a29c13"
sbs_disclaimer_label: wsgi

sbs_mail_sender_name: "SURFnet"
sbs_mail_sender_email: "no-reply@surfnet.nl"

sbs_wiki_link: "https://wiki.surfnet.nl/display/SCZ/SCZ+Public+Space"
