---
# TODO: make sure all of this is necessary; which non-standard packages are we
# using, and do we really neeed them?

# Add an apt key for the ppas by id from a keyserver
- name: Add ppa repository keys
  apt_key: keyserver=keyserver.ubuntu.com id=14AA40EC0831756756D7F66C4F4EA0AAE5267A6C

- name: Ensure all necessary repositories are present
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main

- name: ensure that packages are installed
  apt:
    name:
      - libapache2-mod-php5.6
      - php5.6
      - php5.6-fpm
      - php5.6-ldap
      - php5.6-mbstring
      - php5.6-mcrypt
      - php5.6-mysql
      - php5.6-xsl
    state: present

- name: Ensure php5.6 is used when php is called
  command: update-alternatives --set php /usr/bin/php5.6
  register: result
  changed_when: "result.stdout != ''"

- name: install xdebug
  apt: name=php-xdebug state={{ 'present' if php_debug else 'absent' }}

- name: config xdebug
  blockinfile:
    path: "/etc/php/5.6/apache2/php.ini"
    block: |
      [Xdebug]
      xdebug.remote_enable={{ '1' if php_debug else '0' }}
      xdebug.remote_host={{php_xdebug_host}}
      xdebug.remote_port={{php_xdebug_port}}
