---
- include_vars: "packages.yml"
- include_vars: "repositories.yml"

# Add an apt key for the ppas by id from a keyserver
- name: Add ppa repository keys
  apt_key: keyserver=keyserver.ubuntu.com id=14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
  become: Yes

- name: Ensure all necessary repositories are present
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ repositories }}"
  become: Yes

- name: perform apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 1
  become: Yes

- name: ensure that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages  }}"
  become: Yes

- name: Ensure php5.6 is used when php is called
  command: update-alternatives --set php /usr/bin/php5.6
  become: yes
