---
- name: set up mail relay
  include: mailrelay.yml
  when: "inventory_hostname == mail.relay_host"

- name: set up mail
  include: mailleaf.yml
  when: "inventory_hostname != mail.relay_host"

- name: clean up after exim
  apt: name={{item}} state=absent purge=true
  with_items:
    - exim4
    - exim4-base
    - exim4-config
    - exim4-daemon-light

