---
- name: set up mail relay
  include: mailrelay.yml
  when: "inventory_hostname == mail.relay_host"

- name: set up mail
  include: mailleaf.yml
  when: "inventory_hostname != mail.relay_host"

- name: clean up after exim
  apt:
    state: absent
    purge: true
    name:
      - exim4
      - exim4-base
      - exim4-config
      - exim4-daemon-light

