---
# note: {{playbook_dir}} would probably be nicer, but it turns out that that is
# a relative path, which ssh doesn't understand
ansible_ssh_user: "vagrant"
ansible_ssh_private_key_file: "{{inventory_dir}}/../../.vagrant/id_rsa"

secrets_file: "environments/vm/secrets/all.yml"

admin_email: "admin@scz.vnet"

servers:
  dns:
    - 172.20.1.1
  ntp:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
    - 3.pool.ntp.org

fake_hostnames: true

enable_https: true
http_proto: "http{% if enable_https %}s{% endif %}"

# onderstaande is breekbaar; ansible_default_ipv4 kan best een dhcp-ip zijn
# dat niet in de inventory is gedefinieerd. (afhankelijk van je configuratie
# van libvirt etc)
iprange:
  vpn:
    vm:   "172.20.1.0/24"
  vagrant: "192.168.121.0/24"
  bastion:   "172.20.1.1"
  lb:        "172.20.1.24"
  comanage:  "172.20.1.21"
  mgnt:      "172.20.1.0/24"

mail:
  relay_host: "172.20.1.1"
  relay_to: "outgoing.scz.vnet"
  relay_for:
    - "{{iprange.mgnt}}"
  domain: "scz.vnet"


# poor man's user management
root:
  pw_hash: "$6$rounds=500000$AtgwpGVMAm0fyIf$g4JqeEu8O//KsklaqIEJX6UnQgEtrMTrZdNcp/v/O/G75BjISGZINC\
            rJ0JREkKficMZV5IsdshT9cVACb0cxR1"
users:
  - name: SCZ
    uid: scz
    groups: ['scz','sudo_test','sudo_mgnt','systemd-journal']
    # password 'scz'
    pw_hash: "$6$rounds=500000$OOIfLX7bEQus$krZ/mSucwYN5dK25FlrvxmkMfUa4R585tXwihZFDWbXUVSJXymIeJpq\
              pRvP88TEgaNAXrKMD9qbWYvnSLeDOe."
    sshkey: ""

firewall_v4_incoming:
  - { name: bastion,  src: "{{iprange.bastion}}", dport: "22,80,443", proto: tcp }
  - { name: vnet,     src: "{{iprange.vpn.vm}}",  dport: "22,80,443", proto: tcp }
  - { name: vagrant,  src: "{{iprange.vagrant}}", dport: "22", proto: tcp }

# LDAP definition is here, because we need it in both the Ldap and Comanage groups
ldap_base:
  cn: "John Doe"
  dc: "dc=scz,dc=vnet"
  o: "SCZ"

ldap:
  cn: "{{ ldap_base.cn }}"
  dc: "{{ ldap_base.dc }}"
  o: "{{ ldap_base.o }}"
  basedn: "ou=people,{{ ldap_base.dc }}"
  groupdn: "ou=groups,{{ ldap_base.dc }}"
  binddn: "cn={{ ldap_base.cn }},{{ ldap_base.dc }}"

# Comanage-Proxy database configuration is here, because it is needed in both the
# Proxy and Comanage groups.
comanage_proxy_db: "{{ groups['proxy'][0] }}"
comanage_proxy_db_user: "scz"
comanage_proxy_db_name: "cotosa"
