---
firewall_v4_incoming:
  - { name: bastion,      src: "{{iprange.bastion}}", dport:  "22", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "80", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "{{idp_test_port}}", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "{{sp_test_port}}", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "{{oidc_test_port}}", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "{{google_test_port}}", proto: tcp }
  - { name: vagrant,      src: "{{iprange.vagrant}}", dport:  "22", proto: tcp }
  - { name: vnet,         src: "{{iprange.vpn.vm}}",  dport: "22,80,443", proto: tcp }
