---
enable_ipv6: true
letsencrypt:
  use_staging: false
  acme_challenge_dir: "/var/www/certbot"
  cert_dir: "/etc/letsencrypt/live"

firewall_v4_incoming:
  - { name: bastion,      src: "{{iprange.bastion}}", dport:  "22", proto: tcp }
  - { name: public_http,                              dport:  "80", proto: tcp }
  - { name: public_https,                             dport: "443", proto: tcp }

firewall_v6_incoming:
  - { name: public_http,                              dport: "80",  proto: tcp }
  - { name: public_https,                             dport: "443", proto: tcp }

