---
firewall_v4_incoming:
  - { name: bastion,      src: "{{iprange.bastion}}", dport:   "22", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "389", proto: tcp }
  - { name: comanage,     src: "{{iprange.comanage}}", dport:  "389", proto: tcp }
  - { name: vagrant,      src: "{{iprange.vagrant}}", dport:   "22", proto: tcp }
  - { name: vnet,         src: "{{iprange.vpn.vm}}",  dport: "22,389", proto: tcp }

ldap_user: root
