---
sbs_repository: "{{scz_repo.sbs.src}}"
sbs_version: "{{scz_repo.sbs.version}}"

firewall_v4_incoming:
  - name: loadbalancer
    src: "{{lb_ip}}"
    dport:  "{{sbs_server_port}}"
    proto: tcp

sbs_oidc_authz_endpoint: "https://{{ proxy_hostname }}/SamlSP/OIDC/authorization"
sbs_oidc_token_endpoint: "https://{{ proxy_hostname }}/OIDC/token"
sbs_oidc_userinfo_endpoint: "https://{{ proxy_hostname }}/OIDC/userinfo"
