---
sudo_groups:
  - sudo_test

environment_name: vm
environment_string: "SCZ VM"


hostnames:
  proxy: proxy.vm.scz.vnet
  mdq: mdq.vm.scz.vnet
  consent: cm.vm.scz.vnet
  comanage: comanage.vm.scz.vnet
  ldap: ldap.vm.scz.vnet
  meta: meta.vm.scz.vnet
  oidc: oidc-test.vm.scz.vnet
  sp: sp-test.vm.scz.vnet
  idp: idp-test.vm.scz.vnet

idp_test_port: 81
sp_test_port: 82
oidc_test_port: 83

# TODO: get rid of hardcoded ports for proxy vhosts
loadbalancer:
  - hostname: "{{hostnames.proxy}}"
    http: true
    backend_hosts: "{{groups['vm-proxy']}}"
    backend_port: 8080
  - hostname: "{{hostnames.mdq}}"
    http: true
    backend_hosts: "{{groups['vm-proxy']}}"
    backend_port: 8081
  - hostname: "{{hostnames.consent}}"
    http: true
    backend_hosts: "{{groups['vm-proxy']}}"
    backend_port: 8082
  - hostname: "{{hostnames.comanage}}"
    http: true
    backend_hosts: "{{groups['vm-comanage']}}"
    backend_port: 80
  - hostname: "{{hostnames.meta}}"
    http: true
    backend_hosts: "{{groups['vm-meta']}}"
    backend_port: 80
  - hostname: "{{hostnames.oidc}}"
    http: true
    backend_hosts: "{{groups['vm-client']}}"
    backend_port: "{{oidc_test_port}}"
  - hostname: "{{hostnames.sp}}"
    http: true
    backend_hosts: "{{groups['vm-client']}}"
    backend_port: "{{sp_test_port}}"
  - hostname: "{{hostnames.idp}}"
    http: true
    backend_hosts: "{{groups['vm-client']}}"
    backend_port: "{{idp_test_port}}"
  - hostname: "{{hostnames.ldap}}"
    http: false
    frontend_port: 389
    backend_hosts: "{{groups['vm-ldap']}}"
    backend_port: 389
