---
- name: "clean up php5.6"
  include: "php56-del.yml"

- name: install php packages
  apt:
    state: present
    name:
      - libapache2-mod-php
      - php7.3
      - php7.3-fpm
      - php7.3-ldap
      - php7.3-mbstring
      - php7.3-mysql
      - php7.3-xsl

- name: install xdebug
  apt:
    name: php-xdebug
    state: "{{ 'present' if php_debug else 'absent' }}"

- name: config xdebug
  template:
    src: xdebug.ini.j2
    dest: "/etc/php/7.3/apache2/conf.d/99-xdebug.ini"
