---
- name: Ensure that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - xalan
    - wget

- name: Create project directory
  file: path="{{ metadata_project_dir }}" state=directory mode=0755

- name: Create html directory
  file: path="/var/www/html" state=directory mode=0755

- name: Copy xsl files and shell script in place
  copy: src={{ item }} dest={{ metadata_project_dir }}/{{ item }}
  with_items:
    - idps.xsl
    - sps.xsl
    - rs_coco_nosc.xsl
    - nologo.xsl

- name: Copy xsl processing script script in place
  template: src=create_metadata.j2 dest={{ metadata_project_dir }}/create_metadata mode=0755

- name: Remove obsolete cron file
  file:
    path: /etc/cron.d/create_metadata
    state: absent

- name: Remove old metadata file
  file:
    path: "{{ metadata_project_dir }}/{{ item }}"
    state: absent
  with_items:
    - sc_edugain.xml
    - sc_edugain_rs_coco_nosc.xml
    - sc_edugain_rs_coco_nosc_sps.xml
    - sc_edugain_rs_coco_nosc_idps.xml
    - sc_edugain_rs_coco_nosc_nologo.xml
    - sc_edugain_rs_coco_nosc_nologo_idps.xml
    - sc_edugain_rs_coco_nosc_nologo_sps.xml
    - proxy_idp.xml
    - proxy_sp.xml

- name: Copy metadata service files
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
    - metadata.service
    - metadata.timer
  notify:
    - enable metadata job

- name: Run the metadata cronjob now
  command: "{{ metadata_project_dir }}/create_metadata"
  args:
    chdir: "{{ metadata_project_dir }}"

- name: Install logos
  copy: src={{item}} dest=/var/www/html/{{item}} owner=www-data group=www-data
  with_items:
    - Light-Bulb_icon_by_Till_Teenck.svg
    - Light-Bulb_icon_by_Till_Teenck_200px.png
    - Light-Bulb_icon_by_Till_Teenck_1000px.png
