---
replace:
  -
   regexp: "'login' => 'user'"
   replace: "'login' => '{{ comanage_db_user }}'"
  -
   regexp: "'password' => 'password'"
   replace: "'password' => '{{ comanage_db_password }}'"
  -
   regexp: "'database' => 'database_name'"
   replace: "'database' => '{{ comanage_db }}'"

infodb:
  -
   regexp: "you@localhost"
   replace: "{{ comanage_admin_username }}"

comanage_templates:
  - { src: apache2-comanage.conf.j2, dest: /etc/apache2/conf-available/apache2-comanage.conf }
