---
- name: restart filebeat
  service:  name=filebeat state=restarted
  when: use_logserver
  listen: "restart filebeat"

- name: restart rsyslog
  service:  name=rsyslog state=restarted
  listen: "restart rsyslog"
