---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: reload sysctl settings
  systemd:
    name: systemd-sysctl.service
    state: restarted
  when:
    - environment_name!="vm"

- name: restart journald
  systemd:
    name: systemd-journald.service
    state: restarted

- name: reset journal permissions
  command: "/bin/systemd-tmpfiles --create --exclude-prefix=/dev"

- name: update certificates
  command: update-ca-certificates
