---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: reload sysctl settings
  systemd:
    name: systemd-sysctl.service
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: restart journald
  systemd:
    name: systemd-journald.service
    state: restarted

- name: update certificates
  command: update-ca-certificates
