---
- name: restart nullmailer
  service: name=nullmailer state=restarted

- name: restart postfix
  service: name=postfix state=restarted

- name: postalias
  command: /usr/bin/strace /usr/sbin/postalias hash:/etc/postfix/aliases
  args:
    chdir: /etc/postfix
  notify: restart postfix

- name: postmap virtual
  command: /usr/sbin/postmap hash:virtual
  args:
    chdir: /etc/postfix
  notify: restart postfix

