# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ feature-actions ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Decrypt secret
      - shell: bash
        env: # Set the secret as an input
          secret_vm: ${{ secrets.SECRET_VM }}
        run: echo $secret_vm > secret_vm

      # Run errands
      - name: Run errands
        run: |
          echo "options timeout:5"  | sudo tee -a /etc/resolvconf/resolv.conf.d/tail
          echo "options attempts:5" | sudo tee -a /etc/resolvconf/resolv.conf.d/tail
          sudo service resolvconf restart
          sudo apt-add-repository -y ppa:ansible/ansible-2.9
          sudo apt -q update
          sudo apt -y install ansible bridge-utils
          sudo adduser travis docker
          sudo pip2 install --upgrade jinja2
          pip install yamllint jinja2 pyyaml
          git clone --branch v0.2.9 https://github.com/dw/mitogen.git

      # Run Tests
      - name: Run Tests
        run: ./scripts/travis_tests

      # Runs a single command using the runners shell
      - name: Run start-vm
        run: ./start-vm

      # Destroy secret
      - name: Destroy secret
        run: shred secret_vm