---
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ feature-actions ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: ip addr
      - run: ps aux
      - run: uname -a

      # Decrypt secret
      - name: Copy secret
        shell: bash
        env:
          secret_vm: ${{ secrets.SECRET_VM }}
        run: echo $secret_vm > secret_vm

      # Run errands
      - name: Run errands
        run: |
          #echo "options timeout:5"  | sudo tee -a /etc/resolvconf/resolv.conf.d/tail
          #echo "options attempts:5" | sudo tee -a /etc/resolvconf/resolv.conf.d/tail
          #sudo service resolvconf restart
          sudo apt-add-repository -y ppa:ansible/ansible-2.9
          sudo apt -q update
          sudo apt -y install ansible bridge-utils
          #sudo adduser travis docker
          sudo pip2 install --upgrade jinja2
          pip install yamllint jinja2 pyyaml
          #git clone --branch v0.2.9 https://github.com/dw/mitogen.git

      # Run Syntax check
      - name: Run Syntax check
        run: ./scripts/syntax-check

      # Start container
      - name: Run start-vm
        shell: bash
        run: "./start-vm --tags=none || true"

      - run: "docker ps -a"
      - run: "docker network ls"
      - run: "docker network inspect docker_scznet"
      - run: >
          docker exec -i docker_db_1 bash -c '
          apt update;
          apt install netcat-traditional;
          nc.traditional -v -w3 -l -p 3306;
          nc.traditional -v -w3 -l -p 80'

      # Runs a single command using the runners shell
      - name: Run start-vm
        shell: bash
        run: ./start-vm

      # Runs a single command using the runners shell
      - name: Run start-vm --diff
        env:
          REEANTRANT: 1
        run: ./start-vm --diff

      # Runs a single command using the runners shell
      - name: Run idempotency check...
        run: python ./scripts/check-idempotency-status

      # Destroy secret
      - name: Destroy secret
        run: shred secret_vm
